version: "3"
services:
  blog:
    build: .
    image: blog
    container_name: blog
    platform: linux/amd64
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - cargo-cache:/usr/local/cargo/registry
      - database:/usr/src/app/database
    env_file:
      - .env
    restart: always
    command: |
      cargo run

volumes:
  cargo-cache:
  database:
